language: node_js
node_js:
  - 'lts/*'
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - develop
notifications:
  email: false
install:
  - yarn install
script:
  - yarn validate
  - yarn build
